version: '3.8'

services:
  dev:
    image: maven:3.6.2-jdk-8
    command: sleep inf
    volumes:
      - m2repo:/root/.m2/repository
      - .:/tn                       # io-extentions = mvn install | app = mvn verify



volumes:
  m2repo: